### ISSUE TITLE
ModuleNotFoundError: No module named 'bk_asr.ASRData'

### ISSUE THREAD

**Issue by xiaolinpeter** [WEIFENG2333/AsrTools#26]
![image](https://github.com/user-attachments/assets/5460f1fd-0cc7-494b-a3aa-725737a79b88)
Traceback (most recent call last):
  File "/ai/peterSpace/git_workspace/asr_all_projects/AsrTools/example.py", line 1, in <module>
    from bk_asr import BcutASR, JianYingASR, KuaiShouASR
  File "/ai/peterSpace/git_workspace/asr_all_projects/AsrTools/bk_asr/JianYingASR.py", line 12, in <module>
    from .ASRData import ASRDataSeg
ModuleNotFoundError: No module named 'bk_asr.ASRData'

**Comment by xiaolinpeter** [comment]
![image](https://github.com/user-attachments/assets/10f106ff-46dd-4722-8bae-092b73fd6bdd)

**Comment by WEIFENG2333** [comment]
刚刚发现在git提交时遗漏了部分代码。稍后我commit补充完整，届时你再重新git clone运行代码。

**Comment by WEIFENG2333** [comment]
已经补充
