### ISSUE TITLE
求Mac系统的打包程序

### ISSUE THREAD

**Issue by nuanbig** [WEIFENG2333/AsrTools#40]
### 💡 预期的功能 Expected Feature

我是小白用户，求Mac系统的打包程序，谢谢啦！

**Comment by WEIFENG2333** [comment]
没有mac设备无法打包，目前可以从源码运行。

**Comment by ethansun1986** [comment]
> 没有mac设备无法打包，目前可以从源码运行。
源码运行出现下面的问题，不知道是代码问题还是我的 mac 环境问题
(myenv) ethansun@MacBookAir AsrTools % python3 asr_gui.py
Traceback (most recent call last):
  File "/Users/ethansun/AsrTools/asr_gui.py", line 13, in <module>
    from PyQt5.QtCore import Qt, QRunnable, QThreadPool, QObject, pyqtSignal as Signal, pyqtSlot as Slot, QSize, QThread, \
        pyqtSignal
ModuleNotFoundError: No module named 'PyQt5'
(myenv) ethansun@MacBookAir AsrTools % python asr_gui.py 
Traceback (most recent call last):
  File "asr_gui.py", line 13, in <module>
    from PyQt5.QtCore import Qt, QRunnable, QThreadPool, QObject, pyqtSignal as Signal, pyqtSlot as Slot, QSize, QThread, \
ModuleNotFoundError: No module named 'PyQt5'

**Comment by lakegan** [comment]
你可以先安装python3 然后 终端下cd 到这个文件夹下，运行asr_gui.py

<img width="1140" height="1134" alt="Image" src="https://github.com/user-attachments/assets/cb27d60a-c817-448a-b131-df705da83fc0" />

**Comment by LYQ-DEL** [comment]
咋整啊这是😆

**Comment by lakegan** [comment]
你下载一个trae，是豆包的trae.cn 安装完以后，你让ai agent 去运行，你就说你想运行asr_gui.py，然后它会让你安装依赖包，依赖包全部装好后就可以自动运行了。
